### ISSUE TITLE
Oddity in diff type inference

### ISSUE THREAD

**Issue by mathias-brandewinder** [gbaydin/DiffSharp#4]
I was a bit surprised by the following:

```
#r @"..\packages\DiffSharp.0.5.7\lib\DiffSharp.dll"
open DiffSharp.AD.Forward

let f x = sqrt x
let f' = diff f 
```
Why is f' is of type `val f' : (int -> float)` and not `val f' : (float-> float)` ? Is this a bug, or is there a way to give hints to obtain the proper signature?
Cheers,
Mathias

**Comment by gbaydin** [comment]
Hi, this is because the signature of diff is `f:(Dual->Dual)->x:'a->float` where `x` is `x:'a (requires member op_Explicit)`. This allows any type to be used for `x` if it supports conversion to `float`.

Until the moment you use `f'` it is reported as `f':(int->float)`, but it really isn't. The eventual type of `f'` depends on the value you use it with for the first time. So you can write

```
#r @"..\packages\DiffSharp.0.5.7\lib\DiffSharp.dll"
open DiffSharp.AD.Forward

let f x = sqrt x
let f' = diff f 
let v = f' 2.
```

and you will see that the signature will now be reported as `f':(float->float)`.

I agree that it can look confusing. Should I restrict it to `float` perhaps?

**Comment by mathias-brandewinder** [comment]
Oh I see - thanks so much for the clarification, this is most helpful. I am still wrapping my head around how type inference works with DiffSharp, and, because I tend to use the scripting environment a lot, this has implications on how to deal with type inference. For instance, if I send the code above line-by-line for execution in the interactive, it does produce interesting issues.
I need to think about it some more, because your explanation makes sense - and it seems that restricting the types might come as a limitation in other contexts. In the meanwhile, awesome work! Just started playing with the library, and this is very, very exciting.

**Comment by gbaydin** [comment]
I think it's better to restrict the type of evaluation arguments to `float` all over the library, to prevent future confusion and making it friendlier for line-by-line evaluation. Because `x` already requires the `op_Explicit` conversion to `float`, if someone wants to pass anything other than `float` they can convert before passing. This will go into the 0.5.8 release. Thank you Mathias!
